[package]
name = "lc3_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
signal-hook = "0.3.17"
termios = "0.3.3"

